### ISSUE TITLE
Get a bunch of KeyError when I query data from treeherder

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#111]
I meet a bunch of Keyerror like:

ERROR:root:Error in Downloader 2
Traceback (most recent call last):
  File "src/updatedb.py", line 45, in run
    self.do_job(job_spec)
  File "src/updatedb.py", line 61, in do_job
    uploadResults(data, branch, revision, date)
  File "src/updatedb.py", line 211, in uploadResults
    bugid = notes[-1]['note']
KeyError: 'note'
INFO:root:Downloader 2: 2a326dd181aa - 2016-07-28 07:09:20
ERROR:root:Error in Downloader 1
Traceback (most recent call last):
  File "src/updatedb.py", line 45, in run
    self.do_job(job_spec)
  File "src/updatedb.py", line 61, in do_job
    uploadResults(data, branch, revision, date)
  File "src/updatedb.py", line 211, in uploadResults
    bugid = notes[-1]['note']
KeyError: 'note'
INFO:root:Downloader 1: b8deefd10b85 - 2016-07-28 06:25:05
ERROR:root:Error in Downloader 2
Traceback (most recent call last):
  File "src/updatedb.py", line 45, in run
    self.do_job(job_spec)
  File "src/updatedb.py", line 61, in do_job
    uploadResults(data, branch, revision, date)
  File "src/updatedb.py", line 211, in uploadResults
    bugid = notes[-1]['note']
KeyError: 'note'

When trying to run the updatedb.py. And as I recall, this get note url [Get Notes: https://treeherder.mozilla.org/api/project/mozilla-inbound/note/?job_id=5083103] doesn't work for a long time.

**Comment by MikeLing** [comment]
@jmaher

**Comment by jmaher** [comment]
I assume we are getting this because there are no notes associated with the failure, lets just try/except this code.

**Comment by jmaher** [comment]
@MikeLing is this fixed with the try/except

**Comment by MikeLing** [comment]
yep, I think we could close this issue now :)
