### ISSUE TITLE
updatedb.py has errors when run on seta-dev

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#128]
I was working on running updatedb.py manually and determined that it was failing:
Traceback (most recent call last):
  File "updatedb.py", line 46, in run
    self.do_job(job_spec)
  File "updatedb.py", line 62, in do_job
    uploadResults(data, branch, revision, date)
  File "updatedb.py", line 256, in uploadResults
    session.close()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1052, in close
    self._close_impl(invalidate=False)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1091, in _close_impl
    transaction.close(invalidate)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 457, in close
    self.session.transaction = self._parent
AttributeError: 'NoneType' object has no attribute 'transaction'
INFO:root:Downloading completed

I am not sure what this means, possibly this is causing us troubles when running the script in an automated fashion.

**Comment by jmaher** [comment]
a lot of data was uploaded, but it seems as though we had a connection close and everything fails after that:
2016-09-01 18:17:45,253 INFO sqlalchemy.engine.base.Engine COMMIT
INFO:sqlalchemy.engine.base.Engine:COMMIT
2016-09-01 18:17:45,278 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
2016-09-01 18:17:45,278 INFO sqlalchemy.engine.base.Engine INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
INFO:sqlalchemy.engine.base.Engine:INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
2016-09-01 18:17:45,280 INFO sqlalchemy.engine.base.Engine {'branch': 'mozilla-central', 'failure_classification': '1', 'buildtype': 'opt', 'bugid': '', 'duration': '3024', 'testtype': 'android-test-android-4.3-arm7-api-15/opt-mochitest-20', 'revision': '561fa3ce8c09', 'result': 'success', 'slave': 'i-01150cb04de250eb3', 'build_system_type': 'taskcluster', 'platform': 'android-4-3-armv7-api15', 'date': '2016-09-01 15:02:02', 'failures': '[]'}
INFO:sqlalchemy.engine.base.Engine:{'branch': 'mozilla-central', 'failure_classification': '1', 'buildtype': 'opt', 'bugid': '', 'duration': '3024', 'testtype': 'android-test-android-4.3-arm7-api-15/opt-mochitest-20', 'revision': '561fa3ce8c09', 'result': 'success', 'slave': 'i-01150cb04de250eb3', 'build_system_type': 'taskcluster', 'platform': 'android-4-3-armv7-api15', 'date': '2016-09-01 15:02:02', 'failures': '[]'}
2016-09-01 18:17:45,284 INFO sqlalchemy.engine.base.Engine COMMIT
INFO:sqlalchemy.engine.base.Engine:COMMIT
2016-09-01 18:17:45,287 INFO sqlalchemy.engine.base.Engine COMMIT
INFO:sqlalchemy.engine.base.Engine:COMMIT
2016-09-01 18:17:45,296 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
2016-09-01 18:17:45,296 INFO sqlalchemy.engine.base.Engine INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
INFO:sqlalchemy.engine.base.Engine:INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
2016-09-01 18:17:45,296 INFO sqlalchemy.engine.base.Engine {'branch': 'mozilla-inbound', 'failure_classification': '1', 'buildtype': 'debug', 'bugid': '', 'duration': '1783', 'testtype': 'desktop-test-linux64/debug-mochitest-browser-chrome-6', 'revision': '96ef0dd840e8', 'result': 'success', 'slave': 'i-0e4888fd6a2879a92', 'build_system_type': 'taskcluster', 'platform': 'linux64', 'date': '2016-09-01 08:15:12', 'failures': '[]'}
INFO:sqlalchemy.engine.base.Engine:{'branch': 'mozilla-inbound', 'failure_classification': '1', 'buildtype': 'debug', 'bugid': '', 'duration': '1783', 'testtype': 'desktop-test-linux64/debug-mochitest-browser-chrome-6', 'revision': '96ef0dd840e8', 'result': 'success', 'slave': 'i-0e4888fd6a2879a92', 'build_system_type': 'taskcluster', 'platform': 'linux64', 'date': '2016-09-01 08:15:12', 'failures': '[]'}
2016-09-01 18:17:45,297 INFO sqlalchemy.engine.base.Engine ROLLBACK
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
2016-09-01 18:17:45,299 INFO sqlalchemy.engine.base.Engine COMMIT
INFO:sqlalchemy.engine.base.Engine:COMMIT
WARNING:root:This Connection is closed
/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py:68: SAWarning: An exception has occurred during handling of a previous exception.  The previous exception is:
 <class 'sqlalchemy.exc.ResourceClosedError'> This Connection is closed

  "is:\n %s %s\n" % (self._exc_info[0], self._exc_info[1]))
WARNING:root:This transaction is closed
2016-09-01 18:17:45,600 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
2016-09-01 18:17:45,600 INFO sqlalchemy.engine.base.Engine INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
INFO:sqlalchemy.engine.base.Engine:INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
2016-09-01 18:17:45,601 INFO sqlalchemy.engine.base.Engine {'branch': 'mozilla-central', 'failure_classification': '1', 'buildtype': 'debug', 'bugid': '', 'duration': '1443', 'testtype': 'android-test-android-4.3-arm7-api-15/debug-crashtest-6', 'revision': '18b2446bbf07', 'result': 'success', 'slave': 'i-0a33df0b10a72654c', 'build_system_type': 'taskcluster', 'platform': 'android-4-3-armv7-api15', 'date': '2016-09-01 15:45:39', 'failures': '[]'}
INFO:sqlalchemy.engine.base.Engine:{'branch': 'mozilla-central', 'failure_classification': '1', 'buildtype': 'debug', 'bugid': '', 'duration': '1443', 'testtype': 'android-test-android-4.3-arm7-api-15/debug-crashtest-6', 'revision': '18b2446bbf07', 'result': 'success', 'slave': 'i-0a33df0b10a72654c', 'build_system_type': 'taskcluster', 'platform': 'android-4-3-armv7-api15', 'date': '2016-09-01 15:45:39', 'failures': '[]'}
2016-09-01 18:17:45,603 INFO sqlalchemy.engine.base.Engine COMMIT
INFO:sqlalchemy.engine.base.Engine:COMMIT
2016-09-01 18:17:45,625 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
2016-09-01 18:17:45,625 INFO sqlalchemy.engine.base.Engine INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
INFO:sqlalchemy.engine.base.Engine:INSERT INTO testjobs (slave, result, build_system_type, duration, platform, buildtype, testtype, bugid, branch, revision, date, failure_classification, failures) VALUES (%(slave)s, %(result)s, %(build_system_type)s, %(duration)s, %(platform)s, %(buildtype)s, %(testtype)s, %(bugid)s, %(branch)s, %(revision)s, %(date)s, %(failure_classification)s, %(failures)s) RETURNING testjobs.id
2016-09-01 18:17:45,625 INFO sqlalchemy.engine.base.Engine {'branch': 'mozilla-inbound', 'failure_classification': '1', 'buildtype': 'opt', 'bugid': '', 'duration': '1858', 'testtype': 'android-test-android-4.3-arm7-api-15-gradle/opt-robocop-2', 'revision': 'a3385e09f0c0', 'result': 'success', 'slave': 'i-085a4de7a517cc462', 'build_system_type': 'taskcluster', 'platform': 'android-api-15-gradle', 'date': '2016-09-01 11:34:16', 'failures': '[]'}
INFO:sqlalchemy.engine.base.Engine:{'branch': 'mozilla-inbound', 'failure_classification': '1', 'buildtype': 'opt', 'bugid': '', 'duration': '1858', 'testtype': 'android-test-android-4.3-arm7-api-15-gradle/opt-robocop-2', 'revision': 'a3385e09f0c0', 'result': 'success', 'slave': 'i-085a4de7a517cc462', 'build_system_type': 'taskcluster', 'platform': 'android-api-15-gradle', 'date': '2016-09-01 11:34:16', 'failures': '[]'}
2016-09-01 18:17:45,627 INFO sqlalchemy.engine.base.Engine COMMIT
INFO:sqlalchemy.engine.base.Engine:COMMIT
WARNING:root:'NoneType' object has no attribute 'values'
ERROR:root:Error in Downloader 2
Traceback (most recent call last):
  File "updatedb.py", line 46, in run
    self.do_job(job_spec)
  File "updatedb.py", line 62, in do_job
    uploadResults(data, branch, revision, date)
  File "updatedb.py", line 256, in uploadResults
    session.close()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1052, in close
    self._close_impl(invalidate=False)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1091, in _close_impl
    transaction.close(invalidate)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 457, in close
    self.session.transaction = self._parent
AttributeError: 'NoneType' object has no attribute 'transaction'
INFO:root:Downloader 2: e0eeaca87286 - 2016-09-01 11:22:30
ERROR:root:Error in Downloader 3
Traceback (most recent call last):
  File "updatedb.py", line 46, in run
    self.do_job(job_spec)
  File "updatedb.py", line 62, in do_job
    uploadResults(data, branch, revision, date)
  File "updatedb.py", line 256, in uploadResults
    session.close()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1052, in close
    self._close_impl(invalidate=False)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1091, in _close_impl
    transaction.close(invalidate)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 457, in close
    self.session.transaction = self._parent
AttributeError: 'NoneType' object has no attribute 'transaction'
INFO:root:Downloader 3: f3f97d528c6e - 2016-09-01 10:25:16
ERROR:root:Error in Downloader 1
Traceback (most recent call last):
  File "updatedb.py", line 46, in run
    self.do_job(job_spec)
  File "updatedb.py", line 62, in do_job
    uploadResults(data, branch, revision, date)
  File "updatedb.py", line 256, in uploadResults
    session.close()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1052, in close
    self._close_impl(invalidate=False)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1091, in _close_impl
    transaction.close(invalidate)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 457, in close
    self.session.transaction = self._parent
AttributeError: 'NoneType' object has no attribute 'transaction'
INFO:root:Downloader 1: dedd56fa5c54 - 2016-09-01 10:09:58
ERROR:root:Error in Downloader 4
Traceback (most recent call last):
  File "updatedb.py", line 46, in run
    self.do_job(job_spec)
  File "updatedb.py", line 62, in do_job
    uploadResults(data, branch, revision, date)
  File "updatedb.py", line 256, in uploadResults
    session.close()
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1052, in close
    self._close_impl(invalidate=False)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1091, in _close_impl
    transaction.close(invalidate)
  File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 457, in close
    self.session.transaction = self._parent
AttributeError: 'NoneType' object has no attribute 'transaction'

**Comment by jmaher** [comment]
@MikeLing can you take a look at this?

**Comment by MikeLing** [comment]
Sure thing :)

**Comment by jmaher** [comment]
I have to verify this is fixed with the recent changes to updatedb.py.

**Comment by jmaher** [comment]
I am going to close this, we have had a lot of changes since this bug and seta is running fine in dev and master.
