### ISSUE TITLE
failures.py fails with error updating runnable jobs

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#134]
ubuntu@ouija:~/ouija/tools$ python failures.py
It's going to update your runnable jobs data.
Traceback (most recent call last):
  File "failures.py", line 324, in <module>
    update_runnableapi()
  File "failures.py", line 307, in update_runnableapi
    download_runnable_jobs(new_timestamp, task_id)
  File "failures.py", line 316, in download_runnable_jobs
    data = retry(requests.get, args=(url, ), kwargs={'headers': headers}).json()
  File "/usr/local/lib/python2.7/dist-packages/redo/__init__.py", line 152, in retry
    return action(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 394, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 679, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 616, in generate
    decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 225, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 174, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 152, in read
    data = self._sock.recv(left)
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
ubuntu@ouija:~/ouija/tools$

**Comment by jmaher** [comment]
hmm, this is a server error on treeherder:
https://treeherder.mozilla.org/api/project/mozilla-inbound/runnable_jobs/?decisionTaskID=aXmR4FQeRvCj-VRe3miIVg&format=json

I get a 500 returned.  @armenzg can you look at this?

**Comment by jmaher** [comment]
ok, the treeherder issue is getting fixed- we should make sure the SETA code has try/except around any network code and default to something same.  @MikeLing, are you interested in taking this?

**Comment by MikeLing** [comment]
Sure thing, I'm working on that :)

**Comment by MikeLing** [comment]
@jmaher hmmm, you could see we use redo warp the requests rather than use requests directly in SETA, and redo, I think, has pretty good way to deal with the exception[1]. I don't know why we failed to catch exception in here.

[1] https://github.com/bhearsum/redo/blob/master/redo/__init__.py#L89

**Comment by jmaher** [comment]
I believe it re-raises the exceptions:
https://github.com/bhearsum/redo/blob/master/redo/__init__.py#L120

**Comment by MikeLing** [comment]
Does it look good to you? If so, I will apply it on the other network codes :) @jmaher f?

**Comment by MikeLing** [comment]
This issue should been closed due to this https://github.com/mozilla/ouija/pull/139 pr had been closed.
