### ISSUE TITLE
failure running failures.py on heroku

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#143]
Traceback (most recent call last):
  File "tools/failures.py", line 198, in <module>
    options.method)
  File "tools/failures.py", line 179, in analyze_failures
    to_insert, total_detected = seta.weighted_by_jobtype(failures, target, ignore_failure)
  File "/app/tools/seta.py", line 154, in weighted_by_jobtype
    failures = remove_b2g_jobs(failures)
  File "/app/tools/seta.py", line 141, in remove_b2g_jobs
    for revision, jobtypes in failures.iteritems():
AttributeError: 'list' object has no attribute 'iteritems'
~ $

**Comment by jmaher** [comment]
possibly fixed by:
https://github.com/mozilla/ouija/pull/144
