### ISSUE TITLE
error at the end of running failures.py

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#98]
Total removed 114
Total remaining 985
Total jobs 1099
We will detect 100.00% (670) of the 670 failures
we have 143219 outdate jobs need to remove
Traceback (most recent call last):
  File "failures.py", line 350, in <module>
    options.method)
  File "failures.py", line 283, in analyze_failures
    communicate(failures, to_insert, total_detected, testmode, end_date)
  File "failures.py", line 52, in communicate
    prepare_the_database()
  File "failures.py", line 151, in prepare_the_database
    run_query("delete from seta where jobtype=%s" % job)
  File "failures.py", line 161, in run_query
    cur.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[u'android-4-3-armv7-api11', u'debug', u'cppunit']' at line 1")
ubuntu@ouija:~/ouija/tools$ 

@MikeLing this might be related to the work you have done.

**Comment by jmaher** [comment]
the query we run is:
delete from seta where jobtype=[u'android-4-3-armv7-api11', u'debug', u'cppunit']

changing it to add quotes around the %s seems to work as expected.

**Comment by MikeLing** [comment]
https://github.com/mozilla/ouija/pull/99 @jmaher r?
